"""empty message

Revision ID: 925170a668f3
Revises: 5910fed62b56
Create Date: 2021-05-08 22:52:07.551217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925170a668f3'
down_revision = '5910fed62b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
